#!/bin/bash
#SBATCH -A uot195
#SBATCH --job-name="graph.local"
#SBATCH --output="graph.local.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --export=ALL
#SBATCH --time=10

module load cpu/0.15.4 gcc/7.5.0 openjdk hadoop/3.2.2
SW=/expanse/lustre/projects/uot195/fegaras
export TMPDIR=$HOME/tmp

export PIG_HOME=$SW/pig-0.17.0
PATH="$PIG_HOME/bin:$PATH"
export TMPDIR=$HOME/tmp

pig -x local -param G=small-graph.txt graph.pig

rm -rf /tmp/hadoop
